name: BJUT Query Score

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1,5,9,13 * 1,7 1-5' # 1月和7月 每周工作日 9、13、17、21点（GTM+8）

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python bqs.py
      env:
        SCKEY: ${{ secrets.SCKEY }}
        BQS_USERNAME: ${{ secrets.BQS_USERNAME }}
        BQS_VPN_PW: ${{ secrets.BQS_VPN_PW }}
        BQS_JW_PW: ${{ secrets.BQS_JW_PW }}
      
